name: tiffin
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  get: any
  flutter:
    sdk: flutter
  cloud_firestore: ^4.4.3
  pinput: ^2.2.31
  introduction_screen: ^3.0.1
  cupertino_icons: ^1.0.2
  flutter_timer_countdown: ^1.0.2
  #flutter_otp_text_field: ^1.1.0+2
  jiffy: ^5.0.0
  flutter_svg: ^2.0.2 #for using SVG
  provider: ^6.0.5  #for state management
  syncfusion_flutter_gauges: ^20.2.44
  intl: ^0.17.0-nullsafety.2
  flutter_linkify: ^5.0.2
  shared_preferences: ^2.0.5
  flutter_rating_bar: ^4.0.1
  google_maps_flutter: ^2.2.5
  #image_picker: ^0.7.4
  image_picker: ^0.8.6+4
#  polls: ^1.0.1
  http: ^0.13.5
  path_provider: ^2.0.1
  firebase_auth: ^4.2.9
  firebase_core: ^2.7.0
  table_calendar: ^3.0.6
  flutter_polls: ^0.1.0
  date_picker_timeline: ^1.2.3
  toggle_switch: ^2.0.1
  progress_timeline: ^0.0.5
  percent_indicator: ^4.2.2
  flutter_slidable: ^2.0.0
  scratcher: "^2.2.1"
  confetti: ^0.7.0
  animate_icons: ^2.0.0
  webview_flutter: ^4.0.7
  gradient_borders: ^1.0.0
  flutter_lints: ^2.0.0
  flutter_polyline_points: ^1.0.0
  flutter_gif: any
  auto_size_text: ^3.0.0
#  google_maps_flutter: ^2.2.3
  location: ^4.4.0
  #google_maps_place_picker: ^1.0.1
#  syncfusion_flutter_charts: 20.1.55
#
#  syncfusion_flutter_core: 20.1.55


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true


  assets:
     - assets/images/
     - assets/icons/
     - assets/images/Bg Image.png


  fonts:
    - family: Muli
      fonts:
         - asset: assets/fonts/Muli.ttf
         - asset: assets/fonts/Muli-Bold.ttf
           weight: 700
         - asset: assets/fonts/Muli-Light.ttf
           weight: 300
    - family: Move
      fonts:
        - asset: assets/fonts/MoveMedium.otf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
        - asset: assets/fonts/OpenSans-Medium.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: Vollkorn
      fonts:
        - asset: assets/fonts/Vollkorn-BoldItalic.ttf
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Black.otf
        - asset: assets/fonts/Metropolis-Bold.otf
        - asset: assets/fonts/Metropolis-Light.otf
        - asset: assets/fonts/Metropolis-Medium.otf
        - asset: assets/fonts/Metropolis-Thin.otf
        - asset: assets/fonts/Metropolis-Regular.otf

    - family: SansPro
      fonts:
         - asset: assets/fonts/SourceSansPro-Regular.ttf
  #       - asset: assets/fonts/TrajanPro_Bold.ttf
           weight: 300
         - asset: assets/fonts/SourceSansPro-Light.ttf
           weight: 300
  #
